const Bookdb = [
    {
        "sno" : 1,
        "page"  : 1,
        "title" : " Java for dummies",
        "Auther" : " Barry A. Burd",
        "MContent" : "Programing",
        "programming": "Java",
        "Content" : "Java",
        "ContentB" : "",
        "summary" : "",
        "image" : require("../Assets/bookcovers/programming/java for dummies.jpg"),
        "donwn" : "https://download.e-bookshelf.de/download/0002/6330/87/L-G-0002633087-0004390656.pdf",
    },
    {
        "sno" : 2,
        "page"  : 1,
        "title" : "Game development with Python",
        "Auther" : "Al Sweigart",
        "MContent" : "Programing",
        "programming": "Python",
        "Content" : "Python",
        "ContentB" : "Game Development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/pythondev/Making Games with python and pygames.jpg"),
        "donwn" : "https://inventwithpython.com/makinggames.pdf",
    },
    {
        "sno" : 3,
        "page"  : 1,
        "title" : "Game Development Using Python",
        "Auther" : "James R. Parker",
        "MContent" : "Programing",
        "programming": "Python",
        "Content" : "Python",
        "ContentB" : "Game Development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/pythondev/Game Development Using Python.jpeg"),
        "donwn" : "https://terrorgum.com/tfox/books/gamedevelopmentusingpython.pdf",
    },
    {
        "sno" : 4,
        "page"  : 1,
        "title" : "Effective Java",
        "Auther" : "Joshua Bloch",
        "MContent" : "Programing",
        "programming": "Java",
        "Content" : "Java",
        "ContentB" : "",
        "summary" : "",
        "image" : require("../Assets/bookcovers/programming/efjava.jpeg"),
        "donwn" : "https://kea.nu/files/textbooks/new/Effective%20Java%20%282017%2C%20Addison-Wesley%29.pdf",
    },
    {
        "sno" : 5,
        "page"  : 1,
        "title" : "Smarter Way to Learn JavaScript",
        "Auther" : "Joshua Bloch",
        "MContent" : "Programing",
        "programming": "JavaScript",
        "Content" : "JavaScript",
        "ContentB" : "Web development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/programming/Smarter Way to Learn JavaScript.jpeg"),
        "donwn" : "https://wccftech.com/wp-content/uploads/2014/10/JavaScript.pdf",
    },
    {
        "sno" : 6,
        "page"  : 1,
        "title" : "Eloquent JavaScript",
        "Auther" : "Marijn Haverbeke",
        "MContent" : "Programing",
        "programming": "JavaScript",
        "Content" : "JavaScript",
        "ContentB" : "Web development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/programming/Eloquent JavaScript.jpg"),
        "donwn" : "https://eloquentjavascript.net/Eloquent_JavaScript_small.pdf",
    },
    {
        "sno" : 7,
        "page"  : 1,
        "title" : "Python Crash Course",
        "Auther" : "ERIC MATTHES",
        "MContent" : "Programing",
        "programming": "Python",
        "Content" : "Python",
        "ContentB" : "",
        "summary" : "",
        "image" : require("../Assets/bookcovers/programming/python-crash-course-cover.webp"),
        "donwn" : "https://bedford-computing.co.uk/learning/wp-content/uploads/2015/10/No.Starch.Python.Oct_.2015.ISBN_.1593276036.pdf",
    },
    {
        "sno" : 8,
        "page"  : 1,
        "title" : "Automate the Boring Stuff with Python",
        "Auther" : "AL SWEIGART",
        "MContent" : "Programing",
        "programming": "Python",
        "Content" : "Python",
        "ContentB" : "",
        "summary" : "",
        "image" : require("../Assets/bookcovers/programming/automate the booring stuff with python.jpg"),
        "donwn" : "https://edu.anarcho-copy.org/Programming%20Languages/Python/Automate%20the%20Boring%20Stuff%20with%20Python.pdf",
    },
    {
        "sno" : 9,
        "page"  : 1,
        "title" : "You Don't Know JS: ES6 and Beyond",
        "Auther" : "Kyle Simpson",
        "MContent" : "Programing",
        "programming": "JavaScript",
        "Content" : "ES7",
        "ContentB" : "javascript",
        "summary" : "",
        "image" : require("../Assets/bookcovers/ES6 and Beyond.jpeg"),
        "donwn" : "http://cdn.lxqnsys.com/%E4%BD%A0%E4%B8%8D%E7%9F%A5%E9%81%93%E7%9A%84JavaScript%EF%BC%88%E4%B8%8B%E5%8D%B7%EF%BC%89.pdf",
    },
    {
        "sno" : 10,
        "page"  : 1,
        "title" : "HTML and CSS: Design and Build Websites",
        "Auther" : "Jon Duckett",
        "MContent" : "Web Development",
        "programming": "HTML",
        "Content" : "Web Design",
        "ContentB" : "Front end development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/frontend/html-css.jpg"),
        "donwn" : "https://wtf.tw/ref/duckett.pdf",
    },
    {
        "sno" : 11,
        "page"  : 1,
        "title" : "JavaScript and JQuery: Interactive Front-End Web Development",
        "Auther" : "Jon Duckett",
        "MContent" : "Web Development",
        "programming": "JavaScript",
        "Content" : "Jquery",
        "ContentB" : "Frontend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/frontend/js-jquery.jpg"),
        "donwn" : "https://bedford-computing.co.uk/learning/wp-content/uploads/2015/10/JavaScript-and-JQuery-Interactive-Front-End-Web-Development-Introduction.pdf",
    },
    {
        "sno" : 12,
        "page"  : 1,
        "title" : "FullStack React",
        "Auther" : "",
        "MContent" : "Web Development",
        "programming": "React",
        "Content" : "React.js",
        "ContentB" : "Frontend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/frontend/_full-stack-react-book-hd-png-download.png"),
        "donwn" : "https://demo.smarttrainerlms.com/uploads/0003/trainings/course/45/modules/fullstack-react-book-r30_1510302324482009603.pdf",
    },
    {
        "sno" : 13,
        "page"  : 1,
        "title" : "Learning React, 2nd Edition",
        "Auther" : "Alex Banks and Eve Porcello",
        "MContent" : "Web Development",
        "programming": "React",
        "Content" : "React.js",
        "ContentB" : "Frontend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/frontend/learning react.jpeg"),
        "donwn" : "https://pepa.holla.cz/wp-content/uploads/2016/12/Learning-React.pdf",
    },
    // {
    //     "sno" : 14,
    //     "page"  : 1,
    //     "title" : "",
    //     "Auther" : "",
    //     "MContent" : "Web Development",
    //     "programming": "React",
    //     "Content" : "Next.js",
    //     "ContentB" : "Frontend development",
    //     "summary" : "",
    //     "image" : require(""),
    //     "donwn" : "",
    // },
    // {
    //     "sno" : 15,
    //     "page"  : 1,
    //     "title" : "",
    //     "Auther" : "",
    //     "MContent" : "Web Development",
    //     "programming": "React",
    //     "Content" : "Next.js",
    //     "ContentB" : "Frontend development",
    //     "summary" : "",
    //     "image" : require(""),
    //     "donwn" : "",
    // },
    {
        "sno" : 16,
        "page"  : 1,
        "title" : "Bootstrap in 24 Hours, Sams Teach Yourself ",
        "Auther" : "Jennifer Kyrnin",
        "MContent" : "Web Development",
        "programming": "CSS",
        "Content" : "Boostrap",
        "ContentB" : "Frontend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/frontend/boostrap.jpg"),
        "donwn" : "https://ptgmedia.pearsoncmg.com/images/9780672337048/samplepages/9780672337048.pdf",
    },
    {
        "sno" : 17,
        "page"  : 1,
        "title" : "How I got married to tailwind css",
        "Auther" : "Klaus Fischer",
        "MContent" : "Web Development",
        "programming": "CSS",
        "Content" : "Tailwind Css",
        "ContentB" : "Frontend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/frontend/talilwind.webp"),
        "donwn" : "https://on.notist.cloud/pdf/deck-cf558bb3d5cd2031.pdf",
    },
    {
        "sno" : 18,
        "page"  : 1,
        "title" : "Programming TypeScript",
        "Auther" : "Boris Cherny",
        "MContent" : "Web Development",
        "programming": "TypeScript",
        "Content" : "TypeScript",
        "ContentB" : "Frontend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/programming/typescript.jpeg"),
        "donwn" : "https://books-library.net/files/books-library.net-10132058Ts3U9.pdf",
    },
    {
        "sno" : 19,
        "page"  : 1,
        "title" : "fullstack vue",
        "Auther" : "Hassan Djirdeh",
        "MContent" : "Web Development",
        "programming": "Vue js",
        "Content" : "Vue.js",
        "ContentB" : "Frontend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/frontend/vue.png"),
        "donwn" : "https://dl.ebooksworld.ir/motoman/fullstack-vue-book-r8.www.EBooksWorld.ir.pdf",
    },
    {
        "sno" : 20,
        "page"  : 1,
        "title" : "Angular in Action",
        "Auther" : "",
        "MContent" : "Web Development",
        "programming": "Angular",
        "Content" : "Angular.js",
        "ContentB" : "Frontend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/frontend/ang act.jpeg"),
        "donwn" : "https://pepa.holla.cz/wp-content/uploads/2015/10/AngularJS-in-Action.pdf",
    },
    {
        "sno" : 21,
        "page"  : 2,
        "title" : "Angular: Up and Running",
        "Auther" : "",
        "MContent" : "Web Development",
        "programming": "Angular",
        "Content" : "Angular.js",
        "ContentB" : "Frontend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/frontend/ang up.jpeg"),
        "donwn" : "https://pepa.holla.cz/wp-content/uploads/2015/10/AngularJS-Up-and-Running.pdf",
    },
    {
        "sno" : 22,
        "page"  : 2,
        "title" : "Node.js Design Patterns",
        "Auther" : "Mario Casciaro",
        "MContent" : "Web Development",
        "programming": "JavaScript",
        "Content" : "Node.js",
        "ContentB" : "Backend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/backend/nodepattern.jpg"),
        "donwn" : "http://cdn.lxqnsys.com/NODEJS_DESIGN_PATTERNS_SECOND_EDITION.pdf",
    },
    {
        "sno" : 23,
        "page"  : 1,
        "title" : "Express in Action.",
        "Auther" : "",
        "MContent" : "Web Development",
        "programming": "JavaScript",
        "Content" : "Express js",
        "ContentB" : "Backend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/backend/express act.png"),
        "donwn" : "https://hackerstribe.com/wp-content/uploads/2016/04/Node.js-Express-in-Action.pdf",
    },
    {
        "sno" : 24,
        "page"  : 3,
        "title" : "Pro C# 10 with .NET 6 ",
        "Auther" : "",
        "MContent" : "Web Development",
        "programming": "C#",
        "Content" : ".NET",
        "ContentB" : "Backend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/backend/net6.jpeg"),
        "donwn" : "https://dl.ebooksworld.ir/books/Pro.CSharp.10.with.NET.6.Andrew.Troelsen.Phil.Japikse.Apress.9781484278680.EBooksWorld.ir.pdf",
    },
    {
        "sno" : 25,
        "page"  : 2,
        "title" : "Django for beginners",
        "Auther" : "",
        "MContent" : "Web Development",
        "programming": "Python",
        "Content" : "Django",
        "ContentB" : "Backend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/backend/djangobig.jpg"),
        "donwn" : "https://readthedocs.org/projects/django/downloads/pdf/2.2.x/",
    },
    {
        "sno" : 26,
        "page"  : 2,
        "title" : "Lightweight Django ",
        "Auther" : "Mark Lavin & Julia Elman",
        "MContent" : "Web Development",
        "programming": "Python",
        "Content" : "Django",
        "ContentB" : "Backend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/backend/litDjango.jpg"),
        "donwn" : "https://learn.caktusgroup.com/hubfs/Lightweight-Django-Caktus.pdf",
    },
    {
        "sno" : 27,
        "page"  : 2,
        "title" : "Flask Web Development",
        "Auther" : "",
        "MContent" : "Web Development",
        "programming": "Python",
        "Content" : "Flask",
        "ContentB" : "Backend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/backend/flask_web_development.jpeg"),
        "donwn" : "https://coddyschool.com/upload/Flask_Web_Development_Developing.pdf",
    },
    {
        "sno" : 28,
        "page"  : 2,
        "title" : "Laravel: Up & Running:",
        "Auther" : "Matt Stauffer",
        "MContent" : "Web Development",
        "programming": "PHP",
        "Content" : "Larvel",
        "ContentB" : "Backend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/backend/larvel.png"),
        "donwn" : "https://dl.ebooksworld.ir/motoman/OReilly.Laravel.Up.and.Running.2nd.Edition.www.EBooksWorld.ir.pdf",
    },
    {
        "sno" : 29,
        "page"  : 2,
        "title" : "MongoDB Applied Design Patterns",
        "Auther" : "",
        "MContent" : "Web Development",
        "programming": "Mongodb",
        "Content" : "Mongodb",
        "ContentB" : "Backend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/backend/mongo.jpeg"),
        "donwn" : "https://pepa.holla.cz/wp-content/uploads/2016/07/MongoDB-Applied-Design-Patterns.pdf",
    },
    {
        "sno" : 30,
        "page"  : 2,
        "title" : "Apache: The Definitive Guide, 3rd Edition",
        "Auther" : "",
        "MContent" : "Web Development",
        "programming": "Apache",
        "Content" : "Apache",
        "ContentB" : "Backend development",
        "summary" : "",
        "image" : require("../Assets/bookcovers/backend/apche.jpeg"),
        "donwn" : "https://theswissbay.ch/pdf/Gentoomen%20Library/Networking/Apache/O%27Reilly%20-%20Apache%20The%20Definitive%20Guide%203rd%20Edition.pdf",
    },
    //pending
    // {
    //     "sno" : 31,
    //     "page"  : 2,
    //     "title" : "MySQL Crash Course",
    //     "Auther" : "",
    //     "MContent" : "Web Development",
    //     "programming": "MySQL",
    //     "Content" : "MySQL",
    //     "ContentB" : "Backend development",
    //     "summary" : "",
    //     "image" : require(""),
    //     "donwn" : "https://ptgmedia.pearsoncmg.com/images/9780138223021/samplepages/9780138223021_Sample.pdf",
    // },
    // {
    //     "sno" : 31,
    //     "page"  : 2,
    //     "title" : "MySQL Crash Course",
    //     "Auther" : "",
    //     "MContent" : "Web Development",
    //     "programming": "MySQL",
    //     "Content" : "MySQL",
    //     "ContentB" : "Backend development",
    //     "summary" : "",
    //     "image" : require("../Assets/bookcovers/backend/"),
    //     "donwn" : "https://ptgmedia.pearsoncmg.com/images/9780138223021/samplepages/9780138223021_Sample.pdf",
    // },
    // {
    //     "sno" : 31,
    //     "page"  : 2,
    //     "title" : "MySQL Crash Course",
    //     "Auther" : "",
    //     "MContent" : "Web Development",
    //     "programming": "MySQL",
    //     "Content" : "MySQL",
    //     "ContentB" : "Backend development",
    //     "summary" : "",
    //     "image" : require("../Assets/bookcovers/backend/sql.webp"),
    //     "donwn" : "https://ptgmedia.pearsoncmg.com/images/9780138223021/samplepages/9780138223021_Sample.pdf",
    // },
    // {
    //     "sno" : 32,
    //     "page"  : 2,
    //     "title" : "Bigining Database with postreSQL",
    //     "Auther" : "",
    //     "MContent" : "Web Development",
    //     "programming": "postreSQL",
    //     "Content" : "postreSQL",
    //     "ContentB" : "Backend development",
    //     "summary" : "",
    //     "image" : require("../Assets/bookcovers/backend/"),
    //     "donwn" : "https://theswissbay.ch/pdf/Gentoomen%20Library/Databases/postgresql/Beginning%20Databases%20With%20PostreSQL%20-%20From%20Novice%20To%20Professional%2C%202nd%20Ed%202005.pdf",
    // },
    // {
    //     "sno" : 33,
    //     "page"  : 2,
    //     "title" : "MySQL Crash Course",
    //     "Auther" : "",
    //     "MContent" : "Web Development",
    //     "programming": "MySQL",
    //     "Content" : "MySQL",
    //     "ContentB" : "Backend development",
    //     "summary" : "",
    //     "image" : require("../Assets/bookcovers/backend/"),
    //     "donwn" : "https://ptgmedia.pearsoncmg.com/images/9780138223021/samplepages/9780138223021_Sample.pdf",
    // },
     
]


export const Maxpage = 2;


export default Bookdb;